### PR TITLE
Externalise factsets, fixes #90

### LINKED ISSUE #90: [enhancement] support shared externalised factsets
Reduce the size of onceover and allow other applications to access factsets easily by externalising them to a separate gem

### PR DESCRIPTION
**Pull request by GeoffWilliams**
PR to add support for externalised factsets:
* remove all existing factsets
* update documentation
* change the directories being used for factsets to come from the `puppet_factset` gem
* perform limited testing (use checked out onceover code from local path, tests execute and pass)

### CODE REVIEW

**Comment by beergeek** [comment]
@GeoffWilliams can you please rebase this against the latest? I can then merge this PR

**Comment by GeoffWilliams** [comment]
@beergeek I'm holding off this one for the moment - I didn't notice the facterdb gem when I wrote this PR, we should probably use that one instead (dontmerge).  If I get chance I'll have a go at rejigging this

**Comment by beergeek** [comment]
@GeoffWilliams cool, happy for you to recommend what you think is better.

**Comment by GeoffWilliams** [comment]
Hey mate facterdb in linked issue looks to be the way to go..it may need some extra facts loaded to test all the platforms we want.  This has fallen off my radar for the moment I've had a few other higher priority tasks

On 12 September 2017 4:45:55 PM AEST, beergeek <notifications@github.com> wrote:
>@GeoffWilliams cool, happy for you to recommend what you think is
>better.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/dylanratcliffe/onceover/pull/91#issuecomment-328755190

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by GeoffWilliams** [comment]
abandoned in favour of leaving things alone or facterdb

**Pull request closed without merging**
