### PR TITLE
[WIP] Change HTTP requests to support http(s)_proxy environment variables.

### PR DESCRIPTION
**Pull request by jairojunior**

### CODE REVIEW

**Comment by dylanratcliffe** [comment]
Hey, sorry about this Github has not been giving me notifications -_-. This all looks good to me, will merge

**Comment by dylanratcliffe** [comment]
@jairojunior Released v3.0.9

**Comment by jairojunior** [comment]
Sorry. I was planning to move duplicated code to a single place, but didn't have time for this. Maybe next time. :smile:

**Comment by dylanratcliffe** [comment]
Yeah a little duplication is the least of this codebase's problems. it will get a revamp soon

**Pull request merged**
