### PR TITLE
Shared examples

### PR DESCRIPTION
**Pull request by beergeek**
Allow the inclusion of shared_examples in each test.  Allow for customer matchers.

### CODE REVIEW

**Comment by dylanratcliffe** [comment]
Hey @beergeek I just merged some upstream changes in here, can you please:

- [ ] Re-test to make sure I didn't break anything you were using
- [ ] Mention me when you are done

**Comment by jessereynolds** [comment]
LGTM

**Comment by dylanratcliffe** [comment]
Sorry for how long this has taken. As part of the hackathon this has been somewhat added, however will require refactoring. I'll do that after I have released `onceover-gatekeeper`

**Comment by beergeek** [comment]
@beergeek please rebase to latest version :-)

**Comment by dylanratcliffe** [comment]
@beergeek Any luck working out what's failing here?

**Comment by beergeek** [comment]
@dylanratcliffe not as yet mate. I spent a little time on it yesterday, but there is some fundamental thing failing......the cache directory is not being made and I am trying to figure out why.

**Comment by dylanratcliffe** [comment]
Hey I'm going to close this as I'm cleaning up some old PRs and issues, if you'd like to continue work on this though feel free to reopen!

**Pull request closed without merging**
