### PR TITLE
Fix no hierafile, fixes #111, fixes #104

### LINKED ISSUE #104: Uninformative error when hiera.yaml is missing
When you are missing a hiera.yaml at the root of the control-repo or even in the /spec folder you recieve an uninformative error message indicating the problem is the missing file. 

image

Is the hiera.yaml file a requirement to exist for onceover to be able to do it's work?

### LINKED ISSUE #111: Error if hiera file is not present
Environment:
- rbenv 1.1.1
- ruby 2.2.5p319
- bundler 1.15.1
- onceover 3.2.2

Description:
I tested onceover with our inner project which are not 100% control repo compatible I got error:
```
DEBUG    -> Evaluating template spec_helper.rb.erb
DEBUG    -> Binding variables [:location, :repo, :environmentpath, :modulepath]

Error while running: #<TypeError: no implicit conversion of nil into String>
```
I'm not sure if this scenario is likely (spec test without hiera data), if not I think onceover should show correct error message.

edit:
This is duplicate of issue #104

### PR DESCRIPTION
**Pull request by Mandos**
This is first approach to ruby project, so sorry if some of my ideas are heresy.

Full description is in issue #111 
This pull request should fix error when in project not has hiera configuration file. 
I added some simple rspec test, and debug about variables in erb templates. 

Additionally I clean up project a little bit, according to http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/ I move all entries to gemspec file.

### CODE REVIEW

**Comment by Mandos** [comment]
@dylanratcliffe Any comments on this PR? 

I would like to add some unit (rspec) and acceptance (cucumber) tests to this project and link it to TravisCI but I would like to know if this changes would be welcomed.

**Comment by Mandos** [comment]
@dylanratcliffe Any comments on this PR? 

I would like to add some unit (rspec) and acceptance (cucumber) tests to this project and link it to TravisCI but I would like also to know if this changes would be welcomed.

**Comment by dylanratcliffe** [comment]
Hey @Mandos I can't replicate the issue is the only problem. Can you please give me some steps to replicate so I can test on my side. Removing all my hiera.yaml files has no effect for me

**Comment by Mandos** [comment]
@dylanratcliffe More details are in #111, I see that similar problem is described in #104. Maybe it's linked with Ruby's version?

**Comment by dylanratcliffe** [comment]
@Mandos I can't replicate either #111 or #104. Also nobody has sent me the output with `--trace` which is really what I need to verify the root cause here. If you can give me the output of the issues with `--trace` I should be able to replicate and verify this PR

**Comment by Mandos** [comment]
@dylanratcliffe trace below for:
```
rbenv 1.1.1-2-g615f844
ruby 2.2.5p319
bundler 1.15.3
onceover 3.2.3
```
bundler install used with option --binstubs=.bin

Same result I got when I used **bundle exec onceover** but trace in that case trace is longer so I choose this one
```
$ .bin/onceover run spec -s --trace --debug

DEBUG    -> Reading factsets
DEBUG    -> Evaluating template testconfig_Rakefile.erb
DEBUG    -> Reading /workspace/git/xstream/puppet/ix-admin/environment.conf
DEBUG    -> Evaluating template spec_helper.rb.erb

Error while running: #<TypeError: no implicit conversion of nil into String>
/workspace/git/xstream/puppet/ix-admin/.bundle/ruby/2.2.0/gems/onceover-3.2.3/lib/onceover/controlrepo.rb:355:in `initialize'
/workspace/git/xstream/puppet/ix-admin/.bundle/ruby/2.2.0/gems/onceover-3.2.3/lib/onceover/controlrepo.rb:355:in `new'
/workspace/git/xstream/puppet/ix-admin/.bundle/ruby/2.2.0/gems/onceover-3.2.3/lib/onceover/controlrepo.rb:355:in `hiera_config_file_relative_path'
(erb):14:in `write_spec_helper'
/opt/rbenv/versions/2.2.5/lib/ruby/2.2.0/erb.rb:863:in `eval'
/opt/rbenv/versions/2.2.5/lib/ruby/2.2.0/erb.rb:863:in `result'
/workspace/git/xstream/puppet/ix-admin/.bundle/ruby/2.2.0/gems/onceover-3.2.3/lib/onceover/controlrepo.rb:520:in `evaluate_template'
/workspace/git/xstream/puppet/ix-admin/.bundle/ruby/2.2.0/gems/onceover-3.2.3/lib/onceover/testconfig.rb:259:in `write_spec_helper'
/workspace/git/xstream/puppet/ix-admin/.bundle/ruby/2.2.0/gems/onceover-3.2.3/lib/onceover/runner.rb:34:in `prepare!'
/workspace/git/xstream/puppet/ix-admin/.bundle/ruby/2.2.0/gems/onceover-3.2.3/lib/onceover/cli/run.rb:46:in `block (2 levels) in command'
/workspace/git/xstream/puppet/ix-admin/.bundle/ruby/2.2.0/gems/cri-2.6.1/lib/cri/command.rb:298:in `call'
/workspace/git/xstream/puppet/ix-admin/.bundle/ruby/2.2.0/gems/cri-2.6.1/lib/cri/command.rb:298:in `run_this'
/workspace/git/xstream/puppet/ix-admin/.bundle/ruby/2.2.0/gems/cri-2.6.1/lib/cri/command.rb:251:in `run'
/workspace/git/xstream/puppet/ix-admin/.bundle/ruby/2.2.0/gems/cri-2.6.1/lib/cri/command.rb:264:in `run'
/workspace/git/xstream/puppet/ix-admin/.bundle/ruby/2.2.0/gems/cri-2.6.1/lib/cri/command.rb:264:in `run'
/workspace/git/xstream/puppet/ix-admin/.bundle/ruby/2.2.0/gems/onceover-3.2.3/bin/onceover:7:in `<top (required)>'
.bin/onceover:17:in `load'
.bin/onceover:17:in `<main>'
```

**Comment by Mandos** [comment]
@dylanratcliffe  Any update on this?

**Comment by dylanratcliffe** [comment]
@Mandos I've only just got a chance to really review this. It's great work, especially for a first try. However there have been some merges that have caused conflicts. I've rebased off that and opened a new PR with your changes + others. Please give that one your blessing and I'll merge and release: #119

**Pull request closed without merging**
