### PR TITLE
Allow Facter 4

### PR DESCRIPTION
**Pull request by genebean**
It seems safe to remove the Facter restriction now.

### CODE REVIEW

**Comment by genebean** [comment]
This is intentionally behind master because the changes post-3.18.1 have broken my use of Onceover. I based the PR on the 3.18.1 tag.

**Comment by neomilium** [comment]
> This is intentionally behind master because the changes post-3.18.1 have broken my use of Onceover. I based the PR on the 3.18.1 tag.

(Some) Changes post-3.18.1 break my setup too. Could you give more explanations about this? (probably in a dedicated issue).

Maybe the patch I provided in #292 could fix your setup as it does for me.

**Comment by genebean** [comment]
> Maybe the patch I provided in #292 could fix your setup as it does for me.

Yep... that was it. We include a module in site.pp that fails catalog compilation if certain facts are faked and it seems that Onceover is not setting the certname to that of the factset being tested so it blew up.

**Comment by genebean** [comment]
#289 combined with the manifest thing were my stumbling block

**Review by dylanratcliffe — APPROVED** [review]

**Pull request merged**
