### PR TITLE
[WIP] Use facterdb as main source of facts

### PR DESCRIPTION
**Pull request by mandos**
This PR is open only to start discuss about using facts in onceover. I will add another commits when we agree how this feature should look like.

Now all facts are delivered by json files which are in **factsets** folder or could be given in command line (--facts_dir, --facts_files). Facts are close connected with node name.

New way of deliver would be very similar, facts will be delivered by facterdb and connected with node name, this will be base. Additional system will replace (**by default**) or extend/merge facts from json files. So in **replace mode** system should behave same as before.

@dylanratcliffe Any thoughts?

### CODE REVIEW

**Comment by dylanratcliffe** [comment]
Yeah moving to facterdb is definitely something that I'd be open to. The only thing that I don't want to compromise is the ease of creating factsets, users should still be able to run `puppet facts > blah.json` to generate a factset

**Comment by cdenneen** [comment]
@mandos are you planning on using rspec-puppet-facts?

**Comment by logicminds** [comment]
Also note that when using FacterDB a user can supply custom external facts as well.  
https://github.com/mcanevet/rspec-puppet-facts#suppling-custom-external-facts-through-facterdb

**Comment by dylanratcliffe** [comment]
Hey I'm going to close this as I'm cleaning up some old PRs and issues, if you'd like to continue work on this though feel free to reopen!

**Pull request closed without merging**
